### ISSUE TITLE
A little bug i found

### ISSUE THREAD

**Issue by iRDS** [alessandroTironi/UnityGUIChartEditor#1]
First of all, thanks for this little great library!

I found a small bug about the background color of the chart, is currently a fixed value Color.Black, the line is 289 on the GUIChartEditor script, currently is 

`GL.Color(Color.black);`

and should be 

`GL.Color(CurrentChart.currentBgColor);`

Thanks again fo this great graph drawer!

**Comment by Bamboy** [comment]
I made a fork of this repo and made some improvements & bug fixes. 
https://github.com/Bamboy/UnityGUIChartEditor/tree/master

**Comment by alessandroTironi** [comment]
Hi @Bamboy,
Thank you for your work on the project! I invite you to make a pull request of your forked repository, so that I can accept it and make your changes part of the main project. You can refer to this page: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by Bamboy** [comment]
Hopefully I did that right! I don't use the git terminal, so I did a pull request via my github repo.

**Comment by alessandroTironi** [comment]
I am closing this issue after the pull request. Thanks again for your contribution!
